Repository ZackHolmberg/COMP4350-Project, pull requests merged in 2021-02, with the labels that each got.

#3 Issue 1: Initialize repo and create basic administrative documents
  README.md
  assets/Architecture
  assets/Architecture.png
  assets/BisonCoin.ico
  assets/BisonCoin.png
  assets/ProjectRoadmap.png
  assets/Sprints-1.png
  assets/Sprints-2.png
  assets/logo2.png
  assets/logo3.png
Labels: documentation

#24 19: Initialize front end app and create basic interface
  assets/UI.png
  src/app/bisoncoin/.browserslistrc
  src/app/bisoncoin/.eslintrc.js
  src/app/bisoncoin/.gitignore
  src/app/bisoncoin/README.md
  src/app/bisoncoin/babel.config.js
  src/app/bisoncoin/cypress.json
  src/app/bisoncoin/package-lock.json
  src/app/bisoncoin/package.json
  src/app/bisoncoin/public/index.html
  src/app/bisoncoin/src/App.vue
  src/app/bisoncoin/src/assets/BisonCoin.png
  src/app/bisoncoin/src/assets/logo2.png
  src/app/bisoncoin/src/components/Button.vue
  src/app/bisoncoin/src/components/TextInput.vue
  src/app/bisoncoin/src/main.ts
  src/app/bisoncoin/src/pages/HomePage.vue
  src/app/bisoncoin/src/pages/LoginPage.vue
  src/app/bisoncoin/src/shims-tsx.d.ts
  src/app/bisoncoin/src/shims-vue.d.ts
  src/app/bisoncoin/src/store/index.ts
  src/app/bisoncoin/tests/e2e/.eslintrc.js
  src/app/bisoncoin/tests/e2e/plugins/index.js
  src/app/bisoncoin/tests/e2e/specs/test.js
  src/app/bisoncoin/tests/e2e/support/commands.js
  src/app/bisoncoin/tests/e2e/support/index.js
  src/app/bisoncoin/tsconfig.json
Labels: front end

#38 Update frontend styling and added navigation between components
  src/app/bisoncoin/package-lock.json
  src/app/bisoncoin/package.json
  src/app/bisoncoin/src/App.vue
  src/app/bisoncoin/src/components/Button.vue
  src/app/bisoncoin/src/components/TextInput.vue
  src/app/bisoncoin/src/main.ts
  src/app/bisoncoin/src/pages/HomePage.vue
  src/app/bisoncoin/src/pages/LoginPage.vue
  src/app/bisoncoin/src/style.scss
Labels: front end

#42 8 transactions middleware
  backend/.gitignore
  backend/Dockerfiles/.dockerignore
  backend/Dockerfiles/MiningDockerfile
  backend/Dockerfiles/NginxDockerfile
  backend/Dockerfiles/TransactionsDockerfile
  backend/docker-compose.yml
  backend/services/transactions/endpoints.md
  backend/services/transactions/requirements.txt
  backend/services/transactions/src/routes.py
  backend/services/transactions/tests/functional/test_routes.py
  backend/services/transactions/tests/unit/test_functions.py
  backend/services/transactions/tests/unit/test_models.py
  backend/shared/HttpCodes.py
  backend/shared/ReturnStrings.py
  backend/shared/__init__.py
Labels: Priority: High, Risk: Medium, Transactions, middleware

#51 48 initialize wallet service
  backend/.dockerignore
  backend/Dockerfiles/WalletDockerfile
  backend/docker-compose.yml
  backend/services/nginx/nginx.conf
  backend/services/wallet/endpoints.md
  backend/services/wallet/requirements.txt
  backend/services/wallet/run.py
  backend/services/wallet/src/__init__.py
  backend/services/wallet/src/routes.py
  backend/services/wallet/tests/functional/__init__.py
  backend/services/wallet/tests/functional/test_routes.py
  backend/services/wallet/tests/unit/__init__.py
  backend/services/wallet/tests/unit/test_models.py
Labels: Priority: High, Records, Risk: Medium, middleware

#71 28 create wallet component
  src/backend/.gitignore
  src/backend/blockchain/endpoints.md
  src/backend/blockchain/src/routes.py
  src/backend/services/transaction-api/requirements.txt
  src/backend/services/transaction-api/src/routes.py
  src/backend/services/transaction-api/tests/functional/test_routes.py
  src/backend/services/wallet-api/requirements.txt
  src/backend/services/wallet-api/src/routes.py
  src/backend/services/wallet-api/tests/functional/test_routes.py
  src/backend/shared/HttpCodes.py
  src/backend/shared/ReturnStrings.py
  src/frontend/jest.config.js
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/runE2Es.sh
  src/frontend/src/components/Wallet.vue
  src/frontend/src/pages/HomePage.vue
  src/frontend/src/pages/LoginPage.vue
  src/frontend/src/store/index.ts
  src/frontend/tests/e2e/specs/test.js
  src/frontend/tests/e2e/specs/testAppStartup.js
  src/frontend/tests/e2e/specs/testLogin.js
  src/frontend/tests/e2e/specs/testWallet.js
Labels: Priority: High, front end, middleware
